### PR TITLE
Reuse context in reconciler

### LINKED ISSUE #67: Pass context in reconciliation methods instead of defining a new one
We have few methods of our `ProgressiveRolloutReconciler` structure which they need a context.

Instead of using the context defined inside the `Reconcile` method, we re-define it as a background context. This mean we lose all the information about the deadlines if we ever need to cancel the context for whatever reason.

We should instead propagate the context to the dependent methods

### PR DESCRIPTION
**Pull request by DiogoMCampos**
Fixes #67.

Two questions:
- I haven't touched `requestsForApplicationChange` nor `requestsForSecretChange` as they are called in `handler.EnqueueRequestsFromMapFunc(r.requestsForApplicationChange)` and `handler.EnqueueRequestsFromMapFunc(r.requestsForSecretChange)` respectively. Should we?
- I'm reusing the global `ctx` in tests - is there any better approach?

### CODE REVIEW

**Review by sledigabel — APPROVED** [review]
LGTM, but do we know where is the `ctx` for the `Reconcile` function coming from and who sets it?
the logic being, it might be a context that has nothing to do with the actual context we want propagated (in anticipation of #63)

**Comment by sledigabel** [comment]
> Fixes #67.
> 
> Two questions:
> 
> * I haven't touched `requestsForApplicationChange` nor `requestsForSecretChange` as they are called in `handler.EnqueueRequestsFromMapFunc(r.requestsForApplicationChange)` and `handler.EnqueueRequestsFromMapFunc(r.requestsForSecretChange)` respectively. Should we?
> * I'm reusing the global `ctx` in tests - is there any better approach?


OK So THAT is the answer to my question, the context is initialised there :-)
I think it's ok we can leave that like that for now.

@maruina could prob confirm this.

**Comment by maruina** [comment]
I think we should change `requestsForApplicationChange` and `requestsForSecretChange` as they define they own context (see for example https://github.com/Skyscanner/applicationset-progressive-sync/pull/87/files#diff-a853c97824440aa3801077e1f5661f9087e27091372140f15f89ed5c8d0c5ba6R247)

Regarding the test, I'm not sure about that so I think you can keep the current `ctx`.

**Comment by sledigabel** [comment]
> I think we should change `requestsForApplicationChange` and `requestsForSecretChange` as they define they own context

But if they don't generate the context, what will?
It seems to be that this is the context that gets propagated to the Reconciler?
Presumably the context needs to be instantiated somewhere?

**Comment by maruina** [comment]
> > I think we should change `requestsForApplicationChange` and `requestsForSecretChange` as they define they own context
> 
> But if they don't generate the context, what will?
> It seems to be that this is the context that gets propagated to the Reconciler?
> Presumably the context needs to be instantiated somewhere?

You are correct. I was already thinking in a kubebuilder 3.0 scenario.

**Review by maruina — APPROVED** [review]
LGTM

**Review by aravindvnair99 — APPROVED** [review]

**Pull request merged**
