### PR TITLE
Update release-artifacts.yaml

### PR DESCRIPTION
**Pull request by DiogoMCampos**

### CODE REVIEW

**Comment by sledigabel** [comment]
I'm going to need a bit of background on this

**Comment by DiogoMCampos** [comment]
Sorry - created this on a whim after we noticed the current approach wasn't working. I think this may be a bug with GitHub (or Actions, perhaps), to be honest. **tl;dr:** publishing a release that was previously a draft from `github-actions` does not trigger a `push tags` event.

See https://github.com/release-drafter/release-drafter/issues/876 for a more detailed description.

**Review by sledigabel — APPROVED** [review]
LGTM, will change the event type to a published release, so we can use the UI rather than pushing a tag

**Review by DimitarHristov111 — APPROVED** [review]
Updates the GitHub action config to match the suggested solution here - https://github.com/release-drafter/release-drafter/issues/876. This should fix the issue of not running the action when a new release is created from a draft.

**Pull request merged**
